imports:
  - php

filter:
  paths:
    - src/*

checks:
  php: true

tools:
  php_code_sniffer:
    config:
      standard: PSR2
  php_sim: true
  php_cpd: true
  php_loc: true
  php_hhvm: false
  php_mess_detector: true
  php_pdepend: true
  php_analyzer: true
  sensiolabs_security_checker: true
  php_changetracking: true
  external_code_coverage: false

build:
  environment:
    php: 8.3.0
  nodes:
    analysis:
      tests:
        override:
          # Add the respective Scrutinizer analysis for your language like
          - php-scrutinizer-run
