language: php

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_install:
    - echo $HOSTNAME

install:
    - composer install --dev --no-interaction
    - sudo ./tests/install_ejabberd.sh testuser testpass

before_script:
    - cat behat.yml.dist | sed "s/precise32/$HOSTNAME/" > behat.yml

script:
    - ./vendor/bin/phpunit -c tests --coverage-clover=build/logs/clover.xml
    - ./vendor/bin/behat -c tests/behat.yml

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
    - php vendor/bin/coveralls -v

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
