language: php

php:
    - 5.3.3
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

addons:
  code_climate:
    repo_token: 5619fc9386e65aaf3b57e6978ea07726cbd3bd0ed9198e0811b1248ef371e959

before_install:
    - echo $HOSTNAME
    - export IS_HHVM=$(phpenv version | grep "hhvm" > /dev/null; echo $?)

install:
    - composer install --dev --no-interaction
    - sudo ./tests/provisioner/install_ejabberd.sh testuser testpass
    - sudo ./tests/provisioner/install_dovecot.sh testuser testpass

before_script:
    - cat tests/behat.yml.dist | sed "s/precise32/$HOSTNAME/" > tests/behat.yml

script:
    - ./vendor/bin/phpunit -c tests --coverage-clover=build/logs/clover.xml
    - ./vendor/bin/behat -c tests/behat.yml -f progress

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
    - php vendor/bin/coveralls -v
    - php vendor/bin/test-reporter --stdout > codeclimate.json
    - ./tests/upload_codeclimate.sh

after_failure:
    - cat tests/log/features/behat.*.log

matrix:
    fast_finish: true
