language: php

sudo: true

git:
  depth: 2

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - 8.0

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - XDEBUG_MODE=coverage
    - UPLOAD_ARTIFACTS=0
  include:
    - php: 7.4
      env: UPLOAD_ARTIFACTS=1
  matrix:
    - PREFER_LOWEST=""
    - PREFER_LOWEST="--prefer-lowest"

before_install:
    - echo $HOSTNAME

install:
    - composer update --no-interaction --prefer-stable --prefer-dist --no-suggest --no-scripts --no-plugins $PREFER_LOWEST
    - sudo ./tests/provisioner/install_ejabberd.sh testuser testpass
    - sudo ./tests/provisioner/install_dovecot.sh testuser testpass

before_script:
    - cat behat.yml.dist | sed "s/ubuntu-xenial/$HOSTNAME/" > behat.yml

script:
    - ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
    - ./vendor/bin/behat -c behat.yml -f progress

after_script:
    - ./tests/upload_artefacts.sh

after_failure:
    - cat tests/log/features/behat.*.log
    - sudo tail -n 100 /var/log/dovecot.log
    - sudo tail -n 100 /var/log/ejabberd/ejabberd.log

matrix:
    fast_finish: true

addons:
  code_climate:
    repo_token: 5619fc9386e65aaf3b57e6978ea07726cbd3bd0ed9198e0811b1248ef371e959
