version: '3'
services:
    xmpp:
        image: rroemhild/ejabberd
        hostname: ubuntu-xenial
        volumes:
            - "./tests/config/ejabberd/ejabberd.yml.tpl:/opt/ejabberd/conf/ejabberd.yml.tpl"
            - "./tests/config/ejabberd/ejabberd.db:/opt/ejabberd/database/ejabberd.db"
        environment:
            - XMPP_DOMAIN=ubuntu-xenial
            - "EJABBERD_USERS=testuser@ubuntu-xenial:testpass admin@ubuntu-xenial"
            - EJABBERD_ADMINS=admin@ubuntu-xenial
            - TZ=Europe/Berlin
            - EJABBERD_STARTTLS=false
            - EJABBERD_S2S_SSL=false
            - EJABBERD_SKIP_MAKE_SSLCERT=true
            - EJABBERD_LOGLEVEL=5
            - EJABBERD_DEBUG_MODE=true
            - EJABBERD_AUTH_METHOD=sql
            - EJABBERD_AUTH_PASSWORD_FORMAT=plain
            - EJABBERD_CONFIGURE_ODBC=true
            - EJABBERD_ODBC_TYPE=sqlite
            - EJABBERD_ODBC_DATABASE=/opt/ejabberd/database/ejabberd.db
        ports:
            - "15222:5222"

    mail:
        image: dovecot/dovecot:2.3.18
        volumes:
            - "./tests/config/dovecot/dovecot.conf:/etc/dovecot/dovecot.conf"
            - "./tests/config/dovecot/users:/etc/dovecot/users"
            - "./tests/config/dovecot/auth-passwdfile.conf.ext:/etc/dovecot/auth-passwdfile.conf.ext"
        ports:
            - "11110:110"
