version: '3'
services:
  xmpp:
    image: ejabberd/ecs:${EJABBERD_VERSION:-24.02}
    volumes:
      - "./tests/config/ejabberd/ejabberd.yml:/home/ejabberd/conf/ejabberd.yml"
      - "./tests/config/ejabberd/ejabberd.db:/home/ejabberd/database/ejabberd.db"
    ports:
      - "5222:5222"
      - "5223:5223"
    environment:
      - CTL_ON_CREATE=register testuser localhost testpass

  mail:
    image: dovecot/dovecot:2.3.18
    volumes:
      - "./tests/config/dovecot/dovecot.conf:/etc/dovecot/dovecot.conf"
      - "./tests/config/dovecot/users:/etc/dovecot/users"
      - "./tests/config/dovecot/auth-passwdfile.conf.ext:/etc/dovecot/auth-passwdfile.conf.ext"
    ports:
      - "1110:110"
